### ISSUE TITLE
how to do tests automatically?

### ISSUE THREAD

**Issue by ihabpalamino** [skiera/robotizr#16]
Hello i have some test cases in jira xray and i want them to be executed automatically !if this is possible could u provide me an example of code that could do that and do  tests automatically

**Comment by skiera** [comment]
Hi, Robotizr is a tool to generate Robot Framework tests. So there is no functionality to execute tests, because this is then done by Robot Framework. So you need something that execute that tests cases, like your local IDE or a pipeline.
But don't expect further development of this tools, because I have no time for it.
